version: 2.1

orbs:
  maven: circleci/maven@2.1.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - maven-v1-{{ checksum "pom.xml" }}
      - run:
          name: Tests and quality gates
          command: mvn --batch-mode verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven-v1-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_test_results:
          path: target/failsafe-reports
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: quality/checkstyle-result.xml
      - store_artifacts:
          path: target/spotbugsXml.xml
          destination: quality/spotbugsXml.xml
      - store_artifacts:
          path: target

workflows:
  build-test:
    jobs:
      - test
